config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  resources :jobs
  root "jobs#index"
  get 'searchh', to:"jobs#searchh"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/job.rb
class Job < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        
  validates :f_name, :desc,:role, :email, :password, :password_confirmation, presence: true
  validates :email, format: {with: Devise.email_regexp}
  validates :f_name, length: {minimum:  3, too_short: "%{count} is too small to be a full name"}

  has_many :jobs

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base 
    before_action :configure_permitted_parameters, if: :devise_controller?
    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:f_name, :desc,  :email, :password, :password_confirmation,:role])
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:cat_name)
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show, :searchh] 
  before_action :set_job, only: %i[ show edit update destroy ]
  before_action :correct_user, only: [:edit, :update, :destroy]
  

  # GET /jobs or /jobs.json
  def index
    @jobs = Job.paginate(:page => params[:page], :per_page => 1)
    end
  def searchh 
    @jobs = Job.where("category LIKE ? OR job_title LIKE ?", "%"+ params[:q] +"%", "%"+ params[:q] +"%")

  end
   

  # GET /jobs/1 or /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = current_user.jobs.build
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs or /jobs.json
  def create
    @job = current_user.jobs.build(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to job_url(@job), notice: "Job was successfully created." }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1 or /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to job_url(@job), notice: "Job was successfully updated." }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url, notice: "Job was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  def correct_user
    @job = current_user.jobs.find_by(id: params[:id])
    redirect_to jobs_url, notice: "You are not authorised to make changes to this job" if @job.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_params
      params.require(:job).permit(:job_title, :job_desc, :salary, :category, :user_id, :search)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Cat name:</strong>
    <%= category.cat_name %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :cat_name, style: "display: block" %>
    <%= form.text_field :cat_name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", category %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/jobs/_form.html.erb
<%= form_with(model: job) do |form| %>
  <% if job.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
        <% job.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :job_title, style: "display: block" %>
    <%= form.text_field :job_title %>
  </div>

  <div>
    <%= form.label :job_desc, style: "display: block" %>
    <%= form.text_area :job_desc %>
  </div>

  <div>
    <%= form.label :salary, style: "display: block" %>
    <%= form.text_field :salary %>
  </div>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.select(:category, options_for_select(Category.all.collect{|l| [l.cat_name]}), {}, {class: "form-control"}) %>
  </div>

  
  <div>
  <%= form.label :user_id, style: "display: none"%>
  <%= form.text_field :user_id, value: current_user.id,style:"display: none" %>
  
</div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/jobs/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
  <%= link_to "JobFind",root_path, class:"navbar-brand"%>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <% if user_signed_in?%>   
        <% if current_user.role == "1"%>
        <li class="nav-item">
        <%= link_to "New Job", new_job_path, class:"nav-link active" %>
        </li>
        <%end%>              
        
        <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
        <%= button_to( "Sign out", destroy_user_session_path, method: :delete,class:"nav-link" )%>
        </li>
        
      <li class="nav-item">
        <%= link_to "New Category", new_category_path, class:"nav-link" %>
      </li>
        <%else%>
      
        
        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
      </li>
     
        <%end %>
      </ul>
      <form class="d-flex" role="search" action="/searchh">
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
          
  </div>
</nav>

app/views/jobs/_job.html.erb
<div id="<%= dom_id job %>">
  <p>
    <strong>Job title:</strong>
    <%= job.job_title %>
  </p>

  <p>
    <strong>Job desc:</strong>
    <%= job.job_desc %>
  </p>

  <p>
    <strong>Salary:</strong>
    <%= job.salary %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= job.category %>
  </p>

</div>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render "form", job: @job %>

<br>

<div>
  <%= link_to "Show this job", @job %> |
  <%= link_to "Back to jobs", jobs_path %>
</div>

app/views/jobs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Jobs</h1>
<% @jobs.each do |job| %>
<div class="card" display="inline-block"style="width: 18rem;">

  <div class="card-body">
    <h5 class="card-title"><%= job.job_title %></h5>
    <h6 class="card-subtitle mb-2 text-muted"><%= job.category%></h6>
    <p class="card-text"><%= job.job_desc.truncate(30) + "..." %></p>
    
  
  </div>
  <%= will_paginate @jobs %>
  <div class="container">
 
  <p>
      <%= link_to "Show this job", job, class:"btn btn-primary" %>
    </p>
    </div>
  <% end %>
</div>

<div id="jobs">
  
    
    
  
</div>

app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render "form", job: @job %>

<br>

<div>
  <%= link_to "Back to jobs", jobs_path %>
</div>

app/views/jobs/searchh.erb
<h1> Search Results </h1>
<p style="color: green"><%= notice %></p>

<h1>Jobs</h1>
<% @jobs.each do |job| %>
<div class="card" display="inline-block"style="width: 18rem;">

  <div class="card-body">
    <h5 class="card-title"><%= job.job_title %></h5>
    <h6 class="card-subtitle mb-2 text-muted"><%= job.category%></h6>
    <p class="card-text"><%= job.job_desc.truncate(30) + "..." %></p>
    
  
  </div>
  <div class="container">
 
  <p>
      <%= link_to "Show this job", job, class:"btn btn-primary" %>
    </p>
    </div>
  <% end %>
</div>

<div id="jobs">
  
    
    
  
</div>

app/views/jobs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @job %>

<div>
  <%= link_to "Edit this job", edit_job_path(@job) %> |
  <%= link_to "Back to jobs", jobs_path %>

  <%= button_to "Destroy this job", @job, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jobfind</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <%= render 'jobs/header' %>
  <div class = "container">
  
    <%= yield %>
  </div>
  </body>
</html>